name: update zsxq

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: update new topic 20
      env:
        ZSXQ_TOKEN: ${{ secrets.zsxq_access_token }}
      run: |
        python3 update.py

    - name: Commit and push if changed   # 将README.md更新到仓库
      run: |
        git pull
        git diff
        git config --global user.email "chybet4@gmail.com"
        git config --global user.name "chybet4"
        git add -A
        git commit -m "Updated Readme" || exit
        git push